const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

function convertToBool(text, fault = 'true') {
    return text === fault ? true : false;
}

module.exports = {
SESSION_ID: process.env.SESSION_ID || "ARSLAN-MD~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK0F0aVVoTnhGWnpjWEFLdDUxRDdVU1p6bmFtY1lTQ2NuNE5qUDF5OHdHcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOWdNNFhYbndYd2NaSHRTVFRvQ3JWdHYySGtydmlhd2hwcXJZV24wWVBCVT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJTSVZ5RGc0REtXZ0RkTjZzZUZHVE5hYytWdENFeUdhQ05ZMGNYZVhqT0VNPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI5K0lZV3FKakZBbEtwSEl3aXhZdWwwdmFMYnk3d3dYbnNZcGplRUN2VVgwPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImVLYmRsRThieWl3Y1YwRmlramdIRUZuZXdQV2RveGc1MUt3cFprMVMyV3M9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InhhZ0FJRHdPNHdwV2I5YzN0algwRVlDTlkrRTRRV1lSZDVMQTZ6VXE2MFE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTUJWMHFpSG5QTUlwZ0pXV2xyNktIUVhUM2pLODFEaFVCcS9rOXNpR20yTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS2ROSjNvVUN3YW1TM05Wdzg4K2pDL0VhSjEwOUJYdSsraEdPZUI3Qm9tZz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ii9sWjNMR2hLYmw2YmE3eU1TeTgzbEE1eEhCOG92YnljQ1lzZWpVU1hmc20vVE5NMVp2UHdXUXZ6T0locEZ2S3k0bGtYN3VSVzJOcnZqVzZMZXd4NGlBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjEyLCJhZHZTZWNyZXRLZXkiOiIxeGRqZkZOVVJLK2ZzOVdxdGhjK1ZEWGtEVWJLQkZXNEdRMFFldXNSYUU0PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJYRlhOTjlXWSIsIm1lIjp7ImlkIjoiMjM0NzA3Mjg3MjEzNzoxNUBzLndoYXRzYXBwLm5ldCIsImxpZCI6IjI0NTUxODE0ODA2MzMyNzoxNUBsaWQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ09ueXBYWVF4dmZMeEFZWUFTQUFLQUE9IiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IjhZWVMyVWNZMi9DTVUvTkNmc1czRVBkYkhaWHF0THBqdzJhQy9oU2F4MTA9IiwiYWNjb3VudFNpZ25hdHVyZSI6InVwZjRBbFAwOGtkbUtvNGVQemxWOWwvYTFzMHF3ckNndmxpODFxSEtqejRQN2h0UGU5VG1FNTkzSTlMVTdiWWJraVFuZ1V4ZmtROXcrVWdHdlJYb0FnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJKWmo4Mk5FMXlzajFvMnJQNGxadm9OQTl3aEdNSXM3TGw3RGNodk1sZjZWNEl0Yy9jbXArT1hFM0VIVEFZYzlGQVozVlhTMHFWRzN1OVlqZzFtcjVnUT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjIzNDcwNzI4NzIxMzc6MTVAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCZkdHRXRsSEdOdndqRlB6UW43RnR4RDNXeDJWNnJTNlk4Tm1ndjRVbXNkZCJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FJSUNBPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzU0NDYzMTc3LCJsYXN0UHJvcEhhc2giOiJubTNCYiIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSzU4In0=",
// === SESSION SETTINGS ===
AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN || "true",
AUTO_STATUS_REPLY: process.env.AUTO_STATUS_REPLY || "false",
AUTO_STATUS_REACT: process.env.AUTO_STATUS_REACT || "true",
AUTO_STATUS_MSG: process.env.AUTO_STATUS_MSG || "*SEEN YOUR STATUS BY TANJIRO-MD 🤍*",

// === GROUP & MESSAGE BEHAVIOR ===
ANTI_DELETE: process.env.ANTI_DELETE || "true",
ANTI_DEL_PATH: process.env.ANTI_DEL_PATH || "inbox",
WELCOME: process.env.WELCOME || "true",
ADMIN_EVENTS: process.env.ADMIN_EVENTS || "false",
ANTI_LINK: process.env.ANTI_LINK || "true",
ANTI_LINK_KICK: process.env.ANTI_LINK_KICK || "false",
ANTI_BAD: process.env.ANTI_BAD || "false",
READ_MESSAGE: process.env.READ_MESSAGE || "false",
READ_CMD: process.env.READ_CMD || "false",
AUTO_REACT: process.env.AUTO_REACT || "false",
AUTO_STICKER: process.env.AUTO_STICKER || "false",
AUTO_REPLY: process.env.AUTO_REPLY || "false",
AUTO_TYPING: process.env.AUTO_TYPING || "true",
AUTO_RECORDING: process.env.AUTO_RECORDING || "false",
ALWAYS_ONLINE: process.env.ALWAYS_ONLINE || "true",
ANTI_VV: process.env.ANTI_VV || "true",
MENTION_REPLY: process.env.MENTION_REPLY || "false",
DELETE_LINKS: process.env.DELETE_LINKS || "false",

// === BOT INFO ===
PREFIX: process.env.PREFIX || "!",
BOT_NAME: process.env.BOT_NAME || "TANJIRO-MD",
STICKER_NAME: process.env.STICKER_NAME || "TANJIRO-MD",
OWNER_NAME: process.env.OWNER_NAME || "*ᗪ卂爪丨†*",
OWNER_NUMBER: process.env.OWNER_NUMBER || "2348054671458",
DEV: process.env.DEV || "22871394585",
DESCRIPTION: process.env.DESCRIPTION || "*© NONCHALANT DAMI 🙂*",
MODE: process.env.MODE || "public",
PUBLIC_MODE: process.env.PUBLIC_MODE || "true",

// === CUSTOM MENU STUFF ===
MENU_IMAGE_URL: process.env.MENU_IMAGE_URL || "https://files.catbox.moe/9i3z0o.jpg",
MENU_VIDEO_URL: process.env.MENU_VIDEO_URL || "https://files.catbox.moe/nl99hq.mp4",
MENU_AUDIO_URL: process.env.MENU_AUDIO_URL || "https://files.catbox.moe/s7689r.mp3",
NEWSLETTER_JID: process.env.NEWSLETTER_JID || "120363377534493877@newsletter",

// === CUSTOM REACTS ===
CUSTOM_REACT: process.env.CUSTOM_REACT || "false",
CUSTOM_REACT_EMOJIS: process.env.CUSTOM_REACT_EMOJIS || "💝,💖,💗,❤️‍🩹,❤️,🧡,💛,💚,💙,💜,🤎,🖤,🤍",
};
